
		<div id="footerWrap">
			<section class="footer-utils b2c_0417">
				<!-- b2c_0417 modify : 2탭0170320 class 추가 -->
				<div class="inner">
					<div class="main-notice">
						<h2 class="blind">공지사항</h2>
						<ul class="list-notice">
							<li>
								<p><a href="https://www.lge.co.kr/lgekor/company/notice/noticeDetail.do?noticeSeq=89" target="_blank" title="새창">LG전자 대표사이트 개인정보 처리방침 개정 안내</a></p>
							</li>
						</ul>
					</div>
					<!-- 국가/언어 -->
					<div class="language onM">
						<span class="title">국가/언어 : </span>
						<a href="https://www.lge.co.kr/lgekor/main.do?innerReferrer=Footer" class="onM">대한민국 / 한글</a>
						<button type="button">한국 / 한국어<span class="icon rd-arrow-d01"></span></button> 
						<ul class="list-language">
							<li><a href="https://www.lge.co.kr/lgekor/main.do?innerReferrer=Footer">한국 / 한국어</a></li>
							<li><a href="https://www.lg.com/common/index.jsp?innerReferrer=Footer">Global / English</a></li>
						</ul>
					</div>
				</div>
			</section>
		
			<!-- sitemap -->
			<div class="footer-sitemap b2c_0417">
				<nav class="sitemap">
					<ul class="gnb-list">
						<li>
							<!------ ThinQ ------>
							<a href="https://www.lge.co.kr/lgekor/product/accessory/smart-life/LGThinQMain.do?innerReferrer=Footer"
								class="site-map_tit">LG ThinQ</a>
							<!------ //ThinQ ------>
		
							<!------ SIGNATURE ------>
							<a href="https://www.lge.co.kr/lgekor/lgsignature/lgsignatureMain.do?innerReferrer=Footer" class="onW">LG SIGNATURE</a>
							<div class="site-map_tit onM" role="button" tabindex="0">LG SIGNATURE</div>
							<div class="gnb-depth-container">
								
							</div>
							<!------ //SIGNATURE ------>
							<a href="https://www.lge.co.kr/lgekor/lgobjetcollection/lgobjetcollectionMain.do?innerReferrer=Footer"
								class="site-map_tit">LG Objet Collection</a>
						</li>
						<li>
							<!------ TV/AV ------>
							<a href="#" onclick="return false;" class="onW">TV/AV</a>
							<div class="site-map_tit onM" role="button" tabindex="0">TV/AV</div> <!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //TV/AV ------>
		
							<!------ PC ------>
							<a href="#" onclick="return false;" class="onW">PC/모니터</a>
							<div class="site-map_tit onM" role="button" tabindex="0">PC/모니터</div><!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //PC ------>
						</li>
						<li>
							<!------ 주방가전 ------>
							<a href="#" onclick="return false;" class="onW">주방가전</a>
							<div class="site-map_tit onM" role="button" tabindex="0">주방가전</div><!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //주방가전 ------>
						</li>
						<li>
							<!------ 생활가전 ------>
							<a href="#" onclick="return false;" class="onW">생활가전</a>
							<div class="site-map_tit onM" role="button" tabindex="0">생활가전</div><!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //생활가전 ------>
		
							<!------ 에어컨/에어케어 ------>
							<a href="#" onclick="return false;" class="onW">에어컨/에어케어</a>
							<div class="site-map_tit onM" role="button" tabindex="0">에어컨/에어케어</div> <!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //에어컨/에어케어 ------>
						</li>
						<li>
							<!------ 모바일 ------>
							<a href="#" onclick="return false;" class="onW">모바일</a>
							<div class="site-map_tit onM" role="button" tabindex="0">모바일</div> <!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //모바일 ------>
						</li>
						<li>
							<!------ 뷰티 ------>
							<a href="#" onclick="return false;" class="onW">뷰티/의료기기</a>
							<div class="site-map_tit onM" role="button" tabindex="0">뷰티/의료기기</div> <!-- 2018-06-20 접근성 초점이동 관련 속성 추가 -->
							<div class="gnb-depth-container">
								
							</div>
							<!------ //뷰티 ------>
						</li>
						<li class="onW">
							<!------ B2B ------>
							<a href="https://www.lge.co.kr/kr/business/" target="_blank">B2B</a>
							<div class="gnb-depth-container">
							</div>
							<div class="gnb-utils-container gnb-depth-container onW">
								
							</div> <!-- class="gnb-utils-container" -->
							<!------ //B2B ------>
						</li>
					</ul> <!-- class="gnb-list" -->
				</nav>
			</div>
			<section class="footer-lge">
				<div class="inner">
					<ul class="array shortcut">
						<li><a href="https://www.lge.co.kr/lgekor/company/main.do" target="_blank">회사소개</a></li>
						<li><a href="https://member.lge.co.kr/auth/indivPersonDtl.do?siteGbnCd=01&amp;claTypeCd=02"
								target="_blank">개인정보처리방침</a></li>
						<li><a href="/lgekor/common/commonEventAgreeList.do">이벤트 개인정보처리방침</a></li>
						<li><a href="https://member.lge.co.kr/auth/indivClauseDtl.do?siteGbnCd=01&amp;claTypeCd=01"
								target="_blank">이용약관</a></li>
						<li><a href="/lgekor/common/commonRefuseCollectEmail.do">이메일무단수집거부</a></li>
						<li><a href="javascript:openRequestDmLayer();">소식지 신청</a></li>
						<li><a href="http://ethics.lg.co.kr/index.do" title="새창" target="_blank">정도 경영 사이버 신문고</a></li>
					</ul>
					<!-- 국가/언어 -->
					<div class="language onW">
						<span class="title">국가/언어 : </span>
						<button type="button">한국 / 한국어<span class="icon rd-arrow-d01"></span></button> <!-- 2018-06-20 버튼타입 추가 -->
						<ul class="list-language">
							<li><a href="https://www.lge.co.kr/lgekor/main.do?innerReferrer=Footer">한국 / 한국어</a></li>
		
							<li><a href="https://www.lg.com/common/index.jsp?innerReferrer=Footer">Global / English</a></li>
						</ul>
					</div>
					<ul class="util onW">
						<li class="family tg-slide">
							<button class="tg-btn">FAMILY SITE<span class="icon nav-down"></span></button>
							<ul class="tg-cont" style="display: none;">
								<li><a href="https://www.lgservice.co.kr/main.do" target="_blank">LG전자 서비스센터</a></li>
								<li><a href="http://kr.lgworld.com/web.main.dev" target="_blank">LG Smartworld</a></li>
								<li><a href="https://sales.lgmobile.co.kr/front/login/index.dev" target="_blank" class="mobileStory">LG
										Mobile STORY</a></li>
							</ul>
						</li>
					</ul>
					<script>
						$(document).ready(function () {
							$(".mobileStory").click(function (e) {
								e.preventDefault();
								var url = $(this).attr("href");
								var chk = confirm("해당 사이트는 LG Mobile 판매자 전용 사이트로 일반인들의 출입을 제한합니다. 사이트에 접속 하시겠습니까?");
								if (chk) {
									window.open(url);
								} else {
									return false;
								}
							})
						})
					</script>
					<ul class="util onM">
						<li class="family tg-slide">
							<button class="tg-btn">FAMILY SITE<span class="icon nav-down"></span></button>
							<ul class="tg-cont" style="display: none;">
								<li><a href="https://www.lgservice.co.kr/main.do" target="_blank">LG전자 서비스센터</a></li>
								<li><a href="https://www.lge.co.kr/lgekor/bestshop/main.do" target="_blank">BEST SHOP</a></li>
								<li><a href="https://www.lge.co.kr/kr/business/" target="_blank">LG전자 B2B</a></li>
								<li><a href="http://kr.lgworld.com/web.main.dev" target="_blank">LG Smartworld</a></li>
							</ul>
						</li>
						<li class="certific new_ico"><a href="https://isms.kisa.or.kr/main/ispims/intro/" target="_blank"><span class="text">[인증범위] 대외 B2C, B2B 서비스 운영<br>[유효기간] 2020.01.29~2023.01.28</span></a></li>
					</ul>
					<p class="info">
						대표이사: <strong>권봉석, 배두용</strong>&nbsp;&nbsp;
						사업자등록번호: <strong>107-86-14075</strong><br class="onM">
						통신판매업신고번호: <strong>제1997-00084호</strong><br class="onM">
						대표번호: <strong>02-3777-1114</strong><br>
						주소: <strong>서울시 영등포구 여의대로 128 LG트윈타워</strong><br class="onM">
						제품 및 서비스 문의 : <strong>1544-7777</strong><br class="onM">
						<strong class="copynotice">본 사이트의 모든 콘텐츠는 저작권법의 보호를 받는 바, 무단 전재, 복사, 배포 등을 금합니다.</strong>
						<span class="copyright">Copyright © 2021 LG Electronics. All Rights Reserved.</span>
					</p>
					<p class="notice onW">
						<small class="pims"><a href="https://isms.kisa.or.kr/main/ispims/intro/" target="_blank"> 
							<img src="https://www.lge.co.kr/lgekor/asset/images/web/common/ico_footer_pims.png" alt="정보보호 및 개인정보보호 관리체계 인증"></a>
							<span class="text">[인증범위] 대외 B2C, B2B 서비스 운영<br>[유효기간] 2020.01.29~2023.01.28</span></small>
					</p>
				</div>
			</section>
			<!-- 소식지 신청 -->
			<div id="dmRequest" class="popup">
				<div class="popupCont">
					<strong class="poptit">소식지 신청</strong>
					<div class="popupInfo">
						<form id="dmFrm" name="dmFrm" method="post">
							<p class="message">
								LG전자는 이벤트 및 신제품 안내 등 다양한 정보를 이메일로 전달해 드리고 있습니다.
							</p>
							<fieldset class="forms">
								<legend>이메일 입력</legend>
		
								<p><label for="chargeEmail">이메일 입력 <em class="required">(필수)</em></label></p>
								<p class="controls">
									<input type="text" id="chargeEmail" name="chargeEmail" class="email" title="이메일 아이디 직접입력">
									@
									<input type="text" id="chargeEmail2" name="chargeEmail2" class="domain" title="이메일 도메인 직접입력">
									<select name="chargeEmailDomain" id="chargeEmailDomain" onchange="selEmailDomain(this.value);"
										class="domain" title="이메일 도메인 선택입력">
										<option value="" selected="selected">직접입력</option>
										<option value="paran.com">paran.com</option>
										<option value="hitel.net">hitel.net</option>
									</select>
								</p>
							</fieldset>
		
							<fieldset class="forms">
								<legend>신청구분</legend>
		
								<p class="fl">신청구분</p>
								<p class="controls">
									<input type="checkbox" id="chkPartB2C" name="chkPartB2C" value="Y" checked="checked">
									<label for="chkPartB2C">일반</label>
		
									<input type="checkbox" id="chkPartB2B" name="chkPartB2B" value="Y" onclick="toggleCodeArea();">
									<label for="chkPartB2B">B2B(비즈니스)</label>
								</p>
							</fieldset>
		
							<fieldset id="codeArea" class="forms" style="display: none;">
								<legend>업종선택</legend>
		
								<p>업종선택</p>
								<p class="controls">
									<select name="cPcode" id="code1" onchange="setCode2(this.value, '');" title="업종선택">
										<option value="">업종선택</option>
									</select>
		
									<select name="cCode" id="code2" title="업종선택">
										<option value="">업종선택</option>
									</select>
								</p>
							</fieldset>
							<script>
								$(window.document).ready(function () {
									$('#chkPartB2B').change(function () {
										this.checked ? $('#codeArea').show() : $('#codeArea').hide();
									});
								});
							</script>
		
							<fieldset class="forms">
								<legend>소식지 신청을 위한 약관 동의</legend>
								<p>
									소식지 신청을 위한 약관 동의
								</p>
		
								<div class="box">
									<p class="box-title">
										<!-- <button class="icon plus onM tg-btn on"><span class="ir">열림/닫힘</span></button> -->
										<input type="checkbox" id="cFlag" name="cFlag" value="Y"><label for="cFlag"><em class="required">*</em>
											개인정보 수집 및 이용(필수)</label>
									</p>
									<div class="box-content">
										[ 소식지 서비스 제공을 위한 개인정보 수집 및 이용 ]<br>
										<br>
										서비스 제공을 위하여 이용자의 개인정보를 아래와 같이 수집하고 있습니다.<br>
										1. 수집하는 개인정보 항목<br>
										- 일반 : 이메일, 소식지 수신·개봉 기록<br>
										- B2B(비지니스) : 이메일, 소식지 수신·개봉 기록, 업종<br>
										2. 개인정보 수집·이용 목적<br>
										- 이벤트, 신제품 안내 등 광고성 정보 전달<br>
										3. 개인정보 보유 및 이용기간<br>
										수신거부 시점까지 보관·활용하며 수집 및 이용 목적이 달성된 후 또는 이용자의 동의철회 요구 시에는 해당 정보를 지체 없이 파기합니다.<br>
										※ 고객님께서 개인정보의 수집·이용에 동의하지 않을 권리가 있으며, 미동의 시 서비스를 이용하실 수 없습니다.<br>
									</div>
								</div>
		
								<div class="box">
									<p class="box-title">
										필수위탁고지
									</p>
									<div class="box-content no-scroll">
										LG전자는 개인정보 취급업무 중 서비스 제공에 필요한 필수적 업무를 아래와 같이 외부 전문업체에 위탁하여 운영하고 있으며, 해당 업체는 서비스 이행을 위한 목적으로만 사용됩니다.<br>
										<table style="margin: 20px 0px; width: 100%; border-collapse: collapse;"
											summary="위탁업체 및 위탁 업무 내용에 관한 표 입니다.">
											<caption style="line-height: 0; font-size: 0px; position: absolute;">위탁업체 및 위탁 업무 내용에 관한 표</caption>
											<colgroup>
												<col style="width: 39%;">
												<col>
											</colgroup>
											<thead>
												<tr>
													<th
														style="border-width: 1px 1px medium; border-style: solid solid none; border-color: rgb(204, 204, 204) rgb(204, 204, 204) currentColor; padding: 5px 0px;">
														위탁업체(수탁자)</th>
													<th
														style="border-width: 1px 1px medium; border-style: solid solid none; border-color: rgb(204, 204, 204) rgb(204, 204, 204) currentColor; padding: 5px 0px; border-image: none;">
														위탁업무 내용</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td style="padding: 6px; border: 1px solid #ccc; text-align: center;">
														<p>LG CNS</p>
													</td>
													<td style="padding: 6px; border: 1px solid #ccc; text-align: center;">
														<p>시스템관리, 소식지 서비스 운영관리</p>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
		
								<p class="btns">
									<a href="javascript:goRequestDm();">신청하기</a>
								</p>
							</fieldset>
						</form>
					</div>
					<a href="#none" class="close icon rd-close" title="close"><span class="ir">close</span></a>
				</div>
			</div>
		</div>