<div id="headerWrap" class="has_login">
	<!-- <script>
	</script> -->
	<div class="gnb-main-container b2c_0417">
		<div class="login_area">
			<ul>
				<li class="join"><a href="" onclick="javascript:fnMemInfoJoin();" id="idMemInfoJoin"><span>회원가입</span></a></li>
				<li class="login"><a href="" onclick="javascript:fnLogin();" id="idLogin"><span>로그인</span></a></li>
			</ul>
		</div>
		<h1><a href="https://www.lge.co.kr/lgekor/main.do" class="sp">LG전자</a></h1>
		<nav class="gnb-main">
			<ul class="gnb-list">
				<li>
					<a href="https://www.lge.co.kr/lgekor/product/accessory/smart-life/LGThinQMain.do">LG ThinQ</a>
				</li>
				<li>
					<a href="https://www.lge.co.kr/lgekor/lgsignature/lgsignatureMain.do">LG SIGNATURE</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="/lgekor/lgsignature/lgsignatureMain.do">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion00.png" alt="LG SIGNATURE">
									초프리미엄 가전
									<strong>LG SIGNATURE</strong>
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/lgsignature/lgsignatureMain.do"
										class="no-sibling iconM af">제품정보</a>
									<ul class="gnb-depth3">
										<li>
											<a style="line-height: 1.5;"
												href="/lgekor/product/media/tv/productDetail.do?cateId=1160&prdId=EPRD.348027">올레드 TV</a>
											<ul class="gnb-depth4 onW">
												<li><a href="/lgekor/product/media/tv/productDetail.do?cateId=1160&prdId=EPRD.346665">· OLED
														R</a></li>
												<li><a href="/lgekor/product/media/tv/productDetail.do?cateId=1160&prdId=EPRD.348027">· OLED
														8K</a></li>
												<li><a href="/lgekor/product/media/tv/productDetail.do?cateId=1160&prdId=EPRD.339208">· OLED
														W</a></li>
											</ul>
										</li>
										<li>
											<a style="line-height: 1.5;"
												href="/lgekor/product/kitchen/refrigerator/productDetail.do?cateId=4150&prdId=EPRD.341789">냉장고</a>
											<ul class="gnb-depth4 onW">
												<li><a
														href="/lgekor/product/kitchen/refrigerator/productDetail.do?cateId=4150&prdId=EPRD.341789">·
														정수기형</a></li>
												<li><a
														href="/lgekor/product/kitchen/refrigerator/productDetail.do?cateId=4140&prdId=EPRD.341757">·
														상냉장/하냉동</a></li>
												<li><a
														href="/lgekor/product/kitchen/refrigerator/productDetail.do?cateId=4120&prdId=EPRD.352371">·
														일반형</a></li>
												<li><a
														href="/lgekor/product/kitchen/refrigerator/productDetail.do?cateId=4300&prdId=EPRD.352338">·
														와인셀러</a></li>
											</ul>
										</li>
										<li><a style="line-height: 1.5;"
												href="/lgekor/product/household-appliances/washing-machine/productDetail.do?prdId=EPRD.303459">세탁기</a>
										</li>
										<li><a style="line-height: 1.5;"
												href="/lgekor/product/aircare/air-conditioner/productDetail.do?cateId=3200&prdId=EPRD.344769">에어컨</a>
										</li>
										<li><a style="line-height: 1.5;"
												href="/lgekor/product/aircare/air-cleaner/productDetail.do?cateId=6260&prdId=EPRD.311403">가습
												공기청정기</a></li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit short">
									<a href="/lgekor/lgsignature/lgsignatureMain.do#art_guide" class="no-sibling iconM af">아트 가이드</a>
								</div>
								<div class="unit short">
									<a href="/lgekor/microsite/lgsignature/showroom/modern/index.jsp" class="no-sibling iconM af"
										target="_blank">쇼룸</a>
								</div>
								<div class="unit short">
									<a href="/lgekor/lgsignature/lgsignatureMain.do#locationLink"
										class="no-sibling iconM af signatureTheme">테마 영상</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/lgsignature/brandstory.do"
										class="no-sibling iconM af">브랜드스토리</a>
								</div>
								<div class="unit">
									<a href="/lgekor/microsite/lgsignature/2016/07/26_lgsignature/w/event_list.jsp" target="_blank"
										class="no-sibling iconM af">사진전</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/lgsignature/award.do" class="no-sibling iconM af">수상내역</a>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<a href="https://www.lge.co.kr/lgekor/lgobjetcollection/lgobjetcollectionMain.do">LG Objet Collection</a>
				</li>
				<li>
					<a href="#" onclick="return false;">TV/AV</a>
					<button class="btn-more icon onM">열기/닫기</button>

					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="/lgekor/product/media/tv/productDetail.do?cateId=1160&prdId=EPRD.346665">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion01.png" alt="차원이 다른 TV - LG 올레드 TV UHD">
									차원이 다른
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_oledtv_txt.png" alt="LG 올레드 TV AI ThinQ">
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/media/tv/productMain.do"
										class="no-sibling iconM af">TV</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/product/media/tv/productList.do?cateId=1160">올레드 TV</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/media/tv/productList.do?cateId=1170">나노셀 TV</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/media/tv/productList.do?cateId=1180">울트라 HD TV</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/media/tv/productList.do?cateId=1120">일반 LED TV</a>
										</li>
									</ul>

								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/media/minibeam/productList.do?cateId=1350" class="no-sibling iconM af">프로젝터</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/media/minibeam/productList.do?cateId=1350">초단초점</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/media/minibeam/productList.do?cateId=1340">투사형</a>
										</li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/media/audio/productList.do?cateId=1700"
										class="no-sibling iconM af">AV</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/product/media/audio/productList.do?cateId=1700">사운드바</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/media/audio/productList.do?cateId=1640">무선 스피커</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/media/audio/productList.do?cateId=8470">블루투스 이어폰(톤
												프리)</a></li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/media/audio/productList.do?cateId=1400">오디오/플레이어</a>
										</li>
									</ul>
									<a href="/lgekor/product/media/audio/productDetail.do?cateId=1700&prdId=EPRD.339105" class="theme">LG
										Objet 오디오</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/media/instagramList.do" class="iconM af"
										class="no-sibling iconM af">TV/AV 컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/contents/media/instagramList.do">리뷰</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/media/guideList.do">가이드</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/media/tvadList.do?categoryCd=1000">광고/홍보</a></li>
									</ul>
									<ul class="gnb-depth3-utils">
										<li><a href="/lgekor/microsite/cinebeam/cinebeamMain.do" class="theme">시네빔 화질체험존</a></li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li class="pc">
					<a href="#" onclick="return false;">PC/모니터</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="/lgekor/product/pc/notebook/productDetail.do?cateId=2170&prdId=EPRD.361681">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion02.png" alt="세상의 상식을 그램하다 LG 그램">
									세상의 상식을 그램하다
									<strong>LG gram</strong>
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/pc/notebook/productMain.do"
										class="no-sibling iconM af">노트북</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/notebook/productList.do?cateId=2170">그램</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/notebook/productList.do?cateId=2130">울트라 기어</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/notebook/productList.do?cateId=2110">울트라 PC</a>
										</li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/pc/allinone/productList.do?cateId=2200"
										class="no-sibling iconM af">일체형 PC</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/pc/desktop/productList.do?cateId=2300"
										class="no-sibling iconM af">데스크톱</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/pc/monitor/productList.do?cateId=2450"
										class="no-sibling iconM af">모니터</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/monitor/ultragearmonitorMain.do">울트라기어 게이밍
												모니터</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/monitor/productList.do?cateId=2460">울트라와이드
												모니터</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/monitor/productList.do?cateId=2410">울트라HD
												모니터</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/monitor/productList.do?cateId=2420">PC모니터</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/monitor/productList.do?cateId=2440">TV모니터</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/pc/monitor/productList.do?cateId=2470">IPTV모니터</a>
										</li>
									</ul>
									<ul class="gnb-depth3-utils">
										<li><a href="/lgekor/product/pc/monitor/360monitorMain.do" class="theme">360 모니터</a></li>
									</ul>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/pc/reviewList.do?categoryCd=2000"
										class="no-sibling iconM af">PC/모니터 컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/contents/pc/reviewList.do?categoryCd=2000">리뷰</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/pc/guideList.do?cateId=2000">가이드</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/pc/tvadList.do?categoryCd=2000">광고/홍보</a></li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<a href="#" onclick="return false;">주방가전</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="/lgekor/product/kitchen/refrigerator/productDetail.do?cateId=4150&prdId=EPRD.350872">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion2020.png" alt="냉장고보다 더 필요한 냉장고 얼음정수기냉장고 LG DIOS">
									1등답게, 디오스가 새로움을 OPEN
									<strong>LG DIOS 얼음정수기냉장고</strong>
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productMain.do"
										class="no-sibling iconM af">냉장고</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productList.do?cateId=4150">정수기형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productList.do?cateId=4140">상냉장/하냉동</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productList.do?cateId=4110">양문형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productList.do?cateId=4120">일반형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productList.do?cateId=4130">비즈니스</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/refrigerator/productList.do?cateId=4300">와인셀러</a>
										</li>
									</ul>

								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/kimchi-fridge/productMain.do"
										class="no-sibling iconM af">김치냉장고</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/kimchi-fridge/productList.do?cateId=4210">스탠드형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/kimchi-fridge/productList.do?cateId=4220">뚜껑식형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/kitchen/kimchi-fridge/productList.do?cateId=4230">프리스타일</a>
										</li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/water-purifier/productList.do?cateId=9100"
										class="no-sibling iconM af">정수기</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/makebeer/makebeerVerify.do?cateId=7510"
										class="no-sibling iconM af">맥주 제조기</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/dishwasher/productList.do?cateId=7400"
										class="no-sibling iconM af">식기세척기</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/lightwave-oven/productList.do?cateId=7100"
										class="no-sibling iconM af">광파오븐</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/microwave/productList.do?cateId=7200"
										class="no-sibling iconM af">전자레인지</a>
								</div>
							</li>
							<li class="products-long">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/kitchen/electricRange/electricRangeMain.do"
										class="no-sibling iconM af">전기레인지</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/builtin" class="no-sibling iconM af"
										target="_blank">빌트인가전</a>
								</div>
								<div class="unit long">
									<a href="https://www.lge.co.kr/kr/business/signaturekitchen/signaturekitchenMain.do"
										class="no-sibling iconM af" target="_blank">시그니처 키친 스위트</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/kitchen/reviewList.do?cateId=4000"
										class="no-sibling iconM af">주방가전 <br class="onW" />컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/contents/kitchen/reviewList.do?categoryCd=4000">리뷰</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/contents/kitchen/funAndIssueList.do?cateId=4000">펀&amp;이슈</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/kitchen/guideList.do?cateId=4000">가이드</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/kitchen/tvadList.do?categoryCd=4000">광고/홍보</a>
										</li>
									</ul>
									<ul class="gnb-depth3-utils">
										<li><a href="/lgekor/microsite/rentalcare/myrentalcare.do?cmd=myrentalcareMain" target="_blank">나의
												케어솔루션</a></li>
										<li><a href="/lgekor/microsite/rentalcare/mrcMain.do" target="_blank">케어솔루션 바로가기</a></li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<a href="#" onclick="return false;">생활가전</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a
									href="/lgekor/product/household-appliances/wash-tower/productDetail.do?cateId=5700&prdId=EPRD.359124">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion04.png" alt="국내최초 원바디 세탁건조기">
									국내최초
									<strong>원바디 세탁건조기</strong>
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/wash-tower/productList.do?cateId=5700"
										class="no-sibling iconM af">워시타워</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/washing-machine/productMain.do"
										class="no-sibling iconM af">세탁기</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/washing-machine/productList.do?cateId=5600">트윈워시</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/washing-machine/productList.do?cateId=5100">트롬</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/washing-machine/productList.do?cateId=5200">통돌이</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/washing-machine/productList.do?cateId=5500">미니세탁기</a>
										</li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/drying-machine/productList.do?cateId=5410"
										class="no-sibling iconM af">의류건조기</a>
								</div>
								<div class="unit short">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/styler/productList.do?cateId=5300"
										class="no-sibling iconM af">스타일러</a>
								</div>
							</li>
							<li>
								<div class="unit onW">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6140"
										class="no-sibling iconM af">무선 청소기</a>
									<ul class="gnb-depth3">
										<li><a href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/cordzeroMain.do">코드제로
												A9S</a></li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/cordzeroR9Main.do">코드제로
												R9</a></li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/cordzeroM9Main.do">코드제로
												M9</a></li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6110">로보킹</a>
										</li>
									</ul>
								</div>
								<div class="unit onM">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6140"
										class="no-sibling iconM af">청소기</a>
								</div>
								<div class="unit onW">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6410"
										class="no-sibling iconM af">유선 청소기</a>
									<ul class="gnb-depth3">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6410">싸이킹</a>
										</li>
									</ul>
								</div>
								<div class="unit onM">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6140"
										class="no-sibling iconM af">코드제로 A9</a>
								</div>
								<div class="unit onM">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/vacuum/productList.do?cateId=6180"
										class="no-sibling iconM af">코드제로 R9</a>
								</div>
								<div class="unit onM">
									<a href="" class="no-sibling iconM af">코드제로 T9</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/message-chair/productList.do?cateId=6500"
										class="no-sibling iconM af">안마의자</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/household-appliances/care/productList.do?cateId=6710"
										class="no-sibling iconM af">케어용품</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/household-appliances/reviewList.do?categoryCd=6000"
										class="no-sibling iconM af">생활가전 <br class="onW" />컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/contents/household-appliances/reviewList.do?categoryCd=6000">리뷰</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/contents/household-appliances/guideList.do?cateId=6000">가이드</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/contents/household-appliances/tvadList.do?categoryCd=6000">광고/홍보</a>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<a href="#" onclick="return false;">에어컨/에어케어</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="/lgekor/product/aircare/air-conditioner/productDetail.do?cateId=3200&prdId=EPRD.349940">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion05.png" alt="인공지능 스스로 에어컨 - LG 휘센 에어컨">
									인공지능 스스로 에어컨
									<strong>LG 휘센</strong>
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/aircare/air-conditioner/productMain.do"
										class="no-sibling iconM af">에어컨</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-conditioner/productList.do?cateId=3300">스탠드형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-conditioner/productList.do?cateId=3200">2in1</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-conditioner/productList.do?cateId=3100">3in1</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-conditioner/productList.do?cateId=3400">벽걸이형</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-conditioner/productList.do?cateId=3700">이동식
												에어컨</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/single-business-stand"
												target="_blank">상업용 냉방기</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/single-business-stand"
												target="_blank">상업용 냉난방기</a></li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/aircare/air-cleaner/productList.do?cateId=6240"
										class="no-sibling iconM af">공기청정기</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-cleaner/productList.do?cateId=6240">공기청정기</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/aircare/air-cleaner/productList.do?cateId=6270">휴대용
												공기청정기</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/product/aircare/air-cleaner/productList.do?cateId=6260">가습
												공기청정기</a></li>
									</ul>
									<a href="/lgekor/product/aircare/air-cleaner/productDetail.do?cateId=6260&prdId=EPRD.327961"
										class="theme" style="letter-spacing: -2px;margin-left: -7px;">LG Objet 가습공기청정기</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/aircare/dehumidifier/productList.do?cateId=6230"
										class="no-sibling iconM af">제습기</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/aircare/air-washer/productList.do?cateId=6210"
										class="no-sibling iconM af">가습기</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/aircare/ceilingfan/productList.do?cateId=7800"
										class="no-sibling iconM af">실링팬</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/aircare/care/productList.do?cateId=7710"
										class="no-sibling iconM af">케어용품</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/aircare/reviewList.do?categoryCd=7000"
										class="no-sibling iconM af">에어컨/에어케어 <br class="onW" />컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/contents/aircare/reviewList.do?categoryCd=7000">리뷰</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/aircare/guideList.do?cateId=7000">가이드</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/aircare/tvadList.do?categoryCd=7000">광고/홍보</a>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<a href="#" onclick="return false;">모바일</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="/lgekor/product/mobile/smart-phone/productDetail.do?cateId=0261&prdId=EPRD.358500">
									<img style="margin-bottom:0" src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_wing.png" alt="">
									<p style="margin-bottom:1%;"> 돌리면 보이는 새로움 </p>
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_wing_txt.png" alt="LG wing">
								</a>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/mobile/categoryMain.do"
										class="no-sibling iconM af">스마트폰</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/mobile/smart-phone/productList.do?cateId=0210">전체</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/mobile/smart-phone/productList.do?cateId=0212">프리미엄</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/product/mobile/smart-phone/productList.do?cateId=0217">Q
												시리즈</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/product/mobile/smart-phone/productList.do?cateId=0213">X
												시리즈</a></li>
									</ul>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/mobile/phone/productList.do?cateId=0230"
										class="no-sibling iconM af">피처폰</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<strong>스마트 디바이스</strong>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/product/mobile/tablet/productList.do?cateId=2160">G
												Pad</a></li>
										<li><a href="/lgekor/microsite/lgdualscreen/lgdualscreenMain.do?type=summary">LG 듀얼 스크린 소개</a></li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/download-center/downloadCenterList.do"
										class="iconM af onW">다운로드센터</a>
								</div>
								<div class="unit">
									<a href="/lgekor/microsite/lgpay/lgpayMain.do" class="iconM af onW">LG 페이</a>
								</div>
								<div class="unit">
									<a href="/lgekor/microsite/mobileswitch/main.do" class="iconM af onW">LG 모바일 스위치</a>
								</div>
								<div class="unit theme onM" style="bottom:50px">
								</div>
								<div class="unit theme onM" style="bottom:50px">
									<a href="/lgekor/microsite/lgpay/lgpayMain.do" class="no-sibling iconM af">LG 페이</a>
								</div>
								<div class="unit theme onM" style="bottom:50px">
									<a href="/lgekor/microsite/mobileswitch/main.do" class="theme">LG 모바일 스위치</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/mobile/swUpgradeList.do?cateId=0200&amp;type=function"
										class="no-sibling iconM af">모바일 컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/contents/mobile/reviewList.do?cateId=0200">리뷰</a></li>
										<li class="onW"><a
												href="https://www.lge.co.kr/lgekor/contents/mobile/swUpgradeList.do?cateId=0200&amp;type=function">SW
												업데이트 알리미</a></li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/mobile/tvadList.do?cateId=0200">광고/홍보</a></li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li class="beauty">
					<a href="#" onclick="return false;">뷰티/의료기기</a>
					<button class="btn-more icon onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li class="promotion onW">
								<a href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/beautydeviceMain.do">
									<img src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_promotion06.png" alt="Personal Beauty Clinic LG 프라엘">
									<strong>LG 프라엘</strong>
								</a>
								<p class="mt10" style="margin: 0 auto; width: 250px;"><a
										href="/lgekor/contents/accessory/02_guideDetail.do"><img
											src="https://www.lge.co.kr/lgekor/asset/images/web/temp/gnb_tit_pral.png" alt="나에게 맞는 프라엘 찾기"></a></p>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/beautydeviceMain.do"
										class="no-sibling iconM af">뷰티 디바이스</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8510">LED
												마스크</a></li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8550">LED
												넥케어</a></li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8560">아이케어</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8520">탄력기기</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8530">흡수촉진기</a>
										</li>
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8540">클렌징
												기기</a></li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/medihairMain.do"
										class="no-sibling iconM af">의료기기</a>
									<ul class="gnb-depth3 onW">
										<li><a
												href="https://www.lge.co.kr/lgekor/product/accessory/medihair/productList.do?cateId=8810">메디헤어</a>
										</li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/product/accessory/care/productList.do?cateId=8710"
										class="no-sibling iconM af">케어용품</a>
								</div>
							</li>
							<li class="products-contents">
								<div class="unit">
									<a href="https://www.lge.co.kr/lgekor/contents/accessory/reviewList.do?categoryCd=8000"
										class="no-sibling iconM af">뷰티/의료기기 컨텐츠</a>
									<ul class="gnb-depth3 onW">
										<li><a href="https://www.lge.co.kr/lgekor/contents/accessory/reviewList.do?categoryCd=8000">리뷰</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/accessory/guideList.do?categoryCd=8000">가이드</a>
										</li>
										<li><a href="https://www.lge.co.kr/lgekor/contents/accessory/tvadList.do?categoryCd=8000">광고/홍보</a>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li class="search">
					<a href="#none" class="icon search onW">검색</a>
					<div class="search-container">
						<div class="inner">
							<button class="btn-close icon rd-close onW"><span class="ir">닫기</span></button>
							<form name="GnbSearchForm" id="AKCFrmTop" method="get" action="/lgekor/search/search.jsp">
								<div class="AKCArrowtop" id="AKCArrowTop"></div>
								<fieldset class="search">
									<legend>통합검색</legend>
									<div class="search-word">
										<input type="text" title="검색어 입력" placeholder="검색어를 입력하세요." id="AKCKwdTop" name="GnbKwd">
										<button type="button" class="btn-search icon search" onclick="goGnbSearch();"><span
												class="ir">검색</span></button>
									</div>
									<div class="search-results" id="AKCDivTop" style="display: none;">
										<!-- <iframe id="AKCIfrmTop" name="AKCIfrmTop" src="/lgekor/search/module/akcTop_layer.jsp"
											frameborder="0" scrolling="no" title="검색 프레임">
										</iframe> -->
									</div>
								</fieldset>
							</form>
						</div>
					</div>
				</li>
				<li class="business">
					<a href="https://www.lge.co.kr/kr/business/" target="_blank" class="iconM af">B2B</a>
					<button class="btn-more onM">열기/닫기</button>
					<div class="gnb-depth-container">
						<ul class="gnb-depth2">
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/cooling" target="_blank">냉난방 시스템</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/outdoor-super5" target="_blank">중대형
												빌딩 시스템</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/single-dualvane" target="_blank">중소형
												빌딩 시스템</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/single-multi-v-s-living"
												target="_blank">주거형 시스템</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/chiller-turbo-chiller"
												target="_blank">중앙공조 시스템</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/system-boiler"
												target="_blank">바닥난방/급탕 시스템</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/air-quality.do"
												target="_blank">공기청정솔루션</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/ventilation-ceilingtype"
												target="_blank">환기 시스템</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/household-appliances/lg-FC480SWAB"
												target="_blank">기류 순환 솔루션</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/cooling/cooling-single.do" target="_blank">제어
												솔루션</a></li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/display" target="_blank">디스플레이</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a
												href="https://www.lge.co.kr/kr/business/product/display/digital-signage-list.do?cateId1=CT00000682"
												target="_blank">디지털 사이니지</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/display/signage-summary.do"
												target="_blank">올레드 사이니지</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/display/signage-indoor.do"
												target="_blank">LED 사이니지</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/display/tv-list.do?cateId1=CT00000687"
												target="_blank">TV</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/display/projector-list.do?cateId1=CT00021179"
												target="_blank">프로젝터</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/display/peripherals-list.do?cateId1=CT00021639"
												target="_blank">AV</a></li>
									</ul>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/common/redirectProductDetail.do?cateId1=CT00023761&prdId=MD00053181&cateId2="
										target="_blank" class="theme">LG Objet TV</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/common/redirectProductDetail.do?cateId1=CT00021640&prdId=MD00053141&cateId2="
										target="_blank" class="theme">LG Objet 오디오</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/it" target="_blank">IT/로봇</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a href="https://www.lge.co.kr/kr/business/product/it/computer-list.do?cateId1=CT00021039"
												target="_blank">노트북</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/computer-list.do?cateId1=CT00021042"
												target="_blank">일체형 PC</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/computer-list.do?cateId1=CT00021043"
												target="_blank">데스크톱</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/monitor-list.do?cateId1=CT00000694"
												target="_blank">모니터</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/healthcare-list.do?cateId1=CT00025221"
												target="_blank">의료용 디바이스</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/clouddevice-list.do?cateId1=CT00024259"
												target="_blank">클라우드 디바이스</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/gpad-list.do?cateId1=CT00000698"
												target="_blank">G Pad</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/lg-ARHC81W" target="_blank">로봇</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/it/robot-solution" target="_blank">로봇솔루션</a>
										</li>
									</ul>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/virtual-showroom/" target="_blank" class="theme">IT
										디지털쇼룸</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/energy" target="_blank">에너지</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a href="https://www.lge.co.kr/kr/business/contents/energy/solar-consulting-main.do"
												target="_blank">태양광발전사업 컨설팅</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/energy/solar-list.do?cateId1=CT00000707"
												target="_blank">태양광</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/energy/ess-list.do?cateId1=CT00000715"
												target="_blank">ESS(에너지저장장치)</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/contents/energy/ems-main.do?code=ems01"
												target="_blank">에너지관리솔루션</a></li>
									</ul>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/builtin" target="_blank">빌트인가전</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a href="https://www.lge.co.kr/kr/business/product/builtin/cooling-list.do?cateId1=CT00020104"
												target="_blank">Cooling Line</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/builtin/cooking-list.do?cateId1=CT00020109"
												target="_blank">Cooking Line</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/builtin/living-list.do?cateId1=CT00020112"
												target="_blank">Living Line</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/contents/builtin/faq-list.do" target="_blank">빌트인가전
												컨텐츠</a></li>
									</ul>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/signaturekitchen/signaturekitchenMain.do" target="_blank"
										class="theme" style="letter-spacing: -0.12em;">시그니처 키친 스위트</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/kitchen" target="_blank">주방가전</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00023500"
												target="_blank">냉장고</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00000722"
												target="_blank">와인셀러</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00000727"
												target="_blank">식기세척기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00000723"
												target="_blank">광파오븐</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00000725"
												target="_blank">전자레인지</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00000482"
												target="_blank">전기레인지</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/kitchen/refrigerator-list.do?cateId1=CT00000756"
												target="_blank">정수기</a></li>
									</ul>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/common/redirectProductDetail.do?cateId1=CT00000719&prdId=MD00044623&cateId2="
										target="_blank" class="theme">LG Objet 냉장고</a>
								</div>
							</li>
							<li style="width: 14%;">
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/household-appliances" target="_blank">생활가전/뷰티</a>
									<button class="btn-more onM">열기/닫기</button>
									<ul class="gnb-depth3">
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/washing-machine-list.do?cateId1=CT00000728"
												target="_blank">세탁기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/dryer-list.do?cateId1=CT00024619"
												target="_blank">건조기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/styler-list.do?cateId1=CT00000734"
												target="_blank">스타일러</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/vacuum-list.do?cateId1=CT00025339"
												target="_blank">무선 청소기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/vacuum-list.do?cateId1=CT00021741"
												target="_blank">유선 청소기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/air-conitioner-list.do?cateId1=CT00000493&cateId2="
												target="_blank">에어컨</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/dehumidifier-list.do?cateId1=CT00000735"
												target="_blank">제습기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/air-cleaner-list.do?cateId1=CT00000736"
												target="_blank">공기청정기</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/air-washer-list.do?cateId1=CT00000738"
												target="_blank">가습기</a></li>
										<li><a href="https://www.lge.co.kr/kr/business/product/household-appliances/lg-FC480SWAB"
												target="_blank">실링팬</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/message-chair-list.do?cateId1=CT00021941"
												target="_blank">안마의자</a></li>
										<li><a
												href="https://www.lge.co.kr/kr/business/product/household-appliances/beauty-device-list.do?cateId1=CT00022261"
												target="_blank">뷰티디바이스</a></li>
									</ul>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/product/common/redirectProductDetail.do?cateId1=CT00000737&prdId=MD00044622&cateId2="
										target="_blank" class="theme" style="letter-spacing: -2px;margin-left: -7px;">LG Objet 가습공기청정기</a>
								</div>
							</li>
							<li>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/contents/incase" target="_blank" class="no-sibling">업종</a>
								</div>
								<div class="unit">
									<a href="https://www.lge.co.kr/kr/business/contents/solution" target="_blank"
										class="no-sibling">솔루션</a>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li class="recent onM">
					<a href="/lgekor/mobile/common/retrieveLatelyProductList.do" class="no-sibling iconM af"
						id="headerLatelyProductCnt">최근 본 제품(<mark>0</mark>)</a>
				</li>
			</ul>
			<div class="gnb-utils-container">
				<div class="inner">
					<ol class="array arrow onW">
						<li><a href="https://www.lge.co.kr/lgekor/main.do">홈</a></li>
						<li><a href="#">뷰티/의료기기</a></li>
						<li><a href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/beautydeviceMain.do">뷰티 디바이스</a>
						</li>
						<li><a
								href="https://www.lge.co.kr/lgekor/product/accessory/beauty-device/productList.do?cateId=8560">아이케어</a>
						</li>
						<li>EWN1</li>
					</ol>
					<div class="gnb-su">
						<ul class="gnb-shortcut-list">
							<li><a href="/lgekor/microsite/rentalcare/mrcMain.do?innerReferrer=downMain" target="_blank"
									class="icon rentalcare"><span></span>케어솔루션</a></li>
							<li><a href="/lgekor/bestshop/main.do" target="_blank" class="icon bestshop"><span></span>베스트샵</a></li>
							<li class="onW"><a
									href="https://www.lgbestshopmall.co.kr/OpenLink/1683/?redirectUrl=%2fBestMall%2fHome%2fIndex?"
									target="_blank" class="icon onlineshop"><span></span>온라인몰</a></li>
							<li class="onM"><a
									href="https://m.lgbestshopmall.co.kr/lgeobs/OpenLink/1683/?redirectUrl=%2fBestMall%2fHome%2fToday?"
									target="_blank">온라인몰</a></li>
							<li><a href="/lgekor/bestshop/counsel/counselMain.do?device=w&inflow=lgekor" class="icon counsel"
									target="_blank"><span></span>매장 상담 신청</a></li>
						</ul>
						<ul class="gnb-utils-list">
							<li><a href="/lgekor/event/eventProgressList.do?innerReferrer=downMain" class="icon event">이벤트</a></li>
							<li>
								<a href="/lgekr/membership/main.jsp" target="_blank" class="onW icon">멤버십</a>
								<a href="/lgekor/mobile/membership/membershipMain.do?innerReferrer=downMain" class="onM">멤버십</a>
							</li>
							<li><a href="https://www.lgservice.co.kr/main.do" class="icon" target="_blank">고객서비스/케어용품샵</a></li>
						</ul>
					</div>
				</div>
			</div> 
		</nav>

		<div class="wrap_nav">
			<div class="inner">
				<a href="#none" class="focus_close">전체메뉴닫기</a>
			</div>
			<button type="button" class="btn_close"><span class="screen_out">전체메뉴 닫기</span></button>
		</div>
		<p class="mobile-shortcut onM">
			<a href="" class="icon join" onclick="javascript:fnMemInfoJoin();" id="idMemInfoJoin"><span>회원가입</span></a>
			<a href="" class="icon login" onclick="javascript:fnLogin();" id="idLogin"><span>로그인</span></a>
			<a href="#none" class="icon menu"><span class="onW">메뉴</span></a>
		</p>
		
		<div class="mbg"></div>
		<button class="btn-close icon rd-arrow-r02 onM"><span class="onW">메뉴닫기</span> </button>
	</div>
	<!--// gnb-main-container -->
	<div class="gnb-utils-container">
		<div class="inner">
			<a href="/lgekor/bestshop/shop/retrieveShopMain.do?device=w&amp;inflow=bestshop" class="icon map-point"><span>매장찾기</span></a>
			<a href="#none" class="icon search gnbSearch"><span>검색</span></a>
		</div>
	</div>
	<!--// gnb-utils-container -->
</div>
<!-- header //-->